# Generated by Django 3.2 on 2021-07-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='is_searchable',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='servings_multiplier',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_searchable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredientimage',
            name='image',
            field=models.ImageField(upload_to='ingredient/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings_multiplier',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to='recipe/'),
        ),
    ]
