# Generated by Django 3.2 on 2021-07-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_auto_20210703_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='servings_multiplier',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, max_length=256),
        ),
    ]
