# Generated by Django 3.2 on 2021-07-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0003_auto_20210708_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient_description',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_description',
            field=models.TextField(blank=True),
        ),
    ]
