# Generated by Django 3.2 on 2021-07-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_auto_20210708_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
    ]
